### ISSUE TITLE
Clarify meaning of href field for services

### ISSUE THREAD

**Issue by nichtich** [gbv/daia#13]
The meaning `href` field at service `presentation` and `loan` might not be clear. Without this field, an document SHOULD/MUST (?) be available without further processing. If the field is given, how does a client know what to do with this URL?

**Comment by lahmann** [comment]
Form my understanding `href` SHOULD only be given if it is needed for further processing of the available document, so that without `href` the document SHOULD be available without further processing.
Examples:
- `presentation` + `href` could indicate an ebook limited to oncampus use
- `presentation` + `href` could point to a request dialogue for special collection's items limited to in-house use
- `presentation` - `href` could indicate an item ready for in-house use (präsenz)
- `loan` + `href` could point to a request dialogue for picking up the item
- `loan` - `href` could indicate an item ready for pickup (freihandbereich)

Therefore if a `href` field is given, the client MUST assume that the given URL is needed to perform the service. If no `href` field is given, the client SHOULD assume that the document is available without any further processing, but it's up to the client to perform additional logic in order to forward the service to the user.

**Comment by nichtich** [comment]
Thanks for the comment! This is exactly what `href` was meant for and how it is normally used. There are two more standard service types:
- `interloan` + `href` could point to a request dialogue to initiate an interlibrary loan 
- `interloan` - `href` does not give a hint how to perform interlibrary loan, so it can be assumed to initiate it "as usual"
- `openaccess` + `href` gives an URL to directly access the document. The URL is likely the same as one would get elsewhere (Google etc.) so it is also needed.
- `openaccess` - `href` indicates the document is available without any further processing but the client needs to know how to actually access it

**Comment by lahmann** [comment]
Great. So, that should clarify the meaning of `href` when provided with a service - or do you think there's still a need for further clarification?

**Comment by nichtich** [comment]
I'll include your words rephrased in the spec and close this issue!

On 21. Oktober 2015 11:06:11 MESZ, "André Lahmann" notifications@github.com wrote:

> Great. So, that should clarify the meaning of `href` when provided with
> a service - or do you think there's still a need for further
> clarification?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gbv/daia/issues/13#issuecomment-149828180

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by lahmann** [comment]
Sounds good, thanks!

**Comment by nichtich** [comment]
See version 0.9.5.
