### ISSUE TITLE
Add service type for closed access digital publications accessible via Web

### ISSUE THREAD

**Issue by nichtich** [gbv/daia#20]
If `openaccess` only applies to open digital publications, one might distinguish licensed digital publications. Right now there is no way to easily distinguish a physical book and a licensed ebook. This _might_ be solved by a dedicated `closedaccess` service type.

For general availability:

``` json
"available": [ {
  "service": "closedaccess",
  "href": "...link-to-login-or-info-page...",
  "limitation": [ { "content": "some weird restrictions depending on license"} ]
} ],
```

For patron-specific availability, if the patron can access the document:

``` json
"available": [ {
  "service": "closedaccess",
  "href": "...link-to-proxy-or-whathever-to-access-the-document..."
} ],
```

**Problem:** Some digital publications can only be access within the library or in the IP-range of the library (or possibly VPN). In this case service `presentation` may be a better choice.

In general, access to a licensed digital publication can be affected by dozens of attributes (type of patron, location of patron, agreement to some contract...) and it can come in many flavours (access via proxy, access via VPN, access with DRM on specific platforms, access only on selected machines, access for limited time ...).

Modelling digital licensed might better be done with `limitation`.

An alternative might be a simple boolean flag to indicate digital publications. Data storage mediums such as DVD, however, are physical!

**Comment by lahmann** [comment]
I agree, distinguishing licensed digital publications from licensed "analogue" publications is necessary i.e. in order to evaluate the `href` value appropriately (for physical items this can be a link to a description of the item, for digital items this can be a link to get access to this item).

Therefore I suggest to introduce for items the optional property `type` (as in PAIA for patron) which is list of custom URIs to identify the item types. Those could be of value:
- `http://purl.org/spar/fabio/DigitalManifestation`
  - `http://purl.org/spar/fabio/DigitalItem`
  - `http://purl.org/spar/fabio/DigitalStorageMedium`
- `http://purl.org/spar/fabio/AnalogManifestation`
  - `http://purl.org/spar/fabio/AnalogItem`
  - `http://purl.org/spar/fabio/AnalogStorageMedium`

By having more detailed information available whether this is a digital or analogue manifestation of a document the client would be able to decide how to process the service-properties correctly. This would also apply to the kind of data storage medium being used.

What do you think? Is this a reasonable addition to the DAIA specification?

**Comment by nichtich** [comment]
The `href` field is not the problem. It is specified as
- `document.href` : "web page about the document" 
- `item.href`: "web page about the item"
- `service.href` : "a link required to perform, register or reserve the service"

I neither think that introduction of FRBR concepts really helps. You wrote:

> the client would be able to decide how to process the service-properties correctly

What reasonable methods of processing can be expected? DAIA should better answer "what can be done with an item?" instead of "what type of item is it?". Up to now the difference between digital and analog did not matter to answer the first question. If it is relevant, what answers can be expected for (=what can be done with) digital publications only?

**Comment by nichtich** [comment]
I tend to add a new service type `remote` instead to indicate remote access to an item.
- `presentation`: use within the library
- `loan`: use at home after picking up at the library
- `remote`: use at home without having to visit the library

This still does not differentiate digital and physical but answers the question ("do I have to go to the library to use it?"). Remote does not necessarily imply easy usage via URL, it could require to install some VPN or DRM software and it subsumes mail delivery and digitize-on-demand (both should be visible from field `delay` but not distinguishable without further `limitation` field).

**Comment by lahmann** [comment]
>  "what can be done with an item?"

True, but this depends on the type of the item. Right now for the case of a non-openaccess, digital document having available the service `loan` the `href` property will provide a link to the (limited) direct access of the document (e.g. patron driven acquisition), whereas a physical copy of an item being available for `loan` will probably provide the link for reserving the item. So in one case the user can access the item directly whereas in the other case the user has to interact with the library first in order to get hold of the item (caused by the item being physical).
So, what I want to point out is the services DAIA reports as an answer to "what can be done with an item?" can be ambiguous and limitations do not help either as one would have to reconstruct the material constraints from a certain set of limitations.

> I tend to add a new service type `remote` instead to indicate remote access to an item.

This seems to be a good idea - would this service be limited to digital items or also apply to items being delivered via snailmail (e.g. Subito)?

**Comment by nichtich** [comment]
I think `remote` can apply to both, digital and snailmail. Digital remote access would normaly have no `delay` while snailmail would have a `delay` of some days. Do we actually need to differentiate the following use cases?
- snailmail document delivery (delay of a few days, physical access afterwards)
- digitize on demand (delay of a few hours to weeks, digital access afterwards)

**Comment by lahmann** [comment]
Sorry for the delay. Meanwhile I talked to a colleague and although document via snailmail has become a rare case it does happen and therefore I would rather include this case in the specification than ignore it.
Therefore `remote` would be a useful addition to DAIA services covering all the cases in which the library is only service-wise but not location-wise involved in the process of getting hold of the document. Any further information on the particular terms of the service (including distinction digital vs. analogue delivery) is covered with `limitation`.

**Comment by nichtich** [comment]
Specification (again) turned out more complex than expected. Since DAIA 0.9.8 digital publications and remote access is better covered.
