### ISSUE TITLE
Implication of service 'presentation' by service 'loan'?

### ISSUE THREAD

**Issue by lahmann** [gbv/daia#26]
In a recent discussion (https://github.com/vufind-org/vufind/pull/521) the question arised whether DAIA implementations should show the service `presentation` if the service `loan` is also available.

As `loan` somehow implies `presentation` (the item can be picked up and used in the library) one could argue that `presentation` does not need to be shown as a service (especially as the service `loan` without the implied service `presentation` is quite unusual)?

**Comment by olli-gold** [comment]
In my opinion DAIA should not decide, which implications are common or not; it should only show availabilities without implications. A service should be listed, if its availability is known, so that no assumptions or implications need to be done with the DAIA output. That being said, its only consequent to set the service presentation to available for items, that can be lent and are available for loan. Setting it to unavailable would be false, not setting it would omit a service, which could in fact get set.

**Comment by lahmann** [comment]
@olli-gold, I am not disagreeing with your point of view, the reason for asking this question is whether even records that need to be requested from stack would need to be assigned the service presentation as it would be possible for the user to lend the requested item and use it in the library.
If the presentation service is conceptualized this wide it would (imo) be necessary to provide a hint in the specification: as long as an item that's for loan is not impossible to use in the institution (as e.g. in archives which do not provide a reading room) the service presentation must be provided.

**Comment by nichtich** [comment]
`loan` does not imply `presentation`, especially if limitations apply. However I'd expect to be able to use a book "within the institution or department" (`presentation`) also if I get it for use "outside of the institution or department for a limited time [after] having been picked up there" (`loan`).

The question whether to _show_ presentation service in addition to loan service is another issue, this fully depends on the client and usability. I'd show `presentation` in addition to `loan` only if it comes with less `limitation`, `delay`, and/or `href`.

> question is whether even records that need to be requested from stack would need to be assigned the service presentation as it would be possible for the user to lend the requested item and use it in the library.

In this case both `presentation` and `loan` come with `href` (need to be requested). With the display rule suggested above, `presentation` would be hidden by the client because its not "better" than `loan`.

> provide a hint in the specification: as long as an item that's for loan is not impossible to use in the institution (as e.g. in archives which do not provide a reading room) the service presentation must be provided.

Ok, a DAIA server should not assume any implications between services such as `loan` => `presentation` but include all possible or known services and let the client decide how to reduce this list.

**Comment by lahmann** [comment]
Thanks for the clarification! The addition to the specification is precise and covers this issue.

**Comment by lahmann** [comment]
Has the specification been updated with the above mentioned note regarding implicated services?

**Comment by nichtich** [comment]
[Here](https://gbv.github.io/daia/daia.html#services) the 0.9.9 version of the spec:

> A DAIA server SHOULD NOT omit services because of assumed implications between service types (for instance most times an item is available for loan it is also available for presentation) but include all service types it knows about.

**Comment by lahmann** [comment]
Great! Thanks!
