### ISSUE TITLE
Express various pickup locations for available item

### ISSUE THREAD

**Issue by lahmann** [gbv/daia#27]
In large libraries alternative pick up locations are not uncommon. The current DAIA specification covers storage information (institution - department - storage). How should various pickup locations for available items be expressed? Using limitations, i.e., accompanying the available service with the locations where it could be picked up as limitations each? Or is this an issue that needs to be addressed in the DAIA specificiation?

**Comment by nichtich** [comment]
This is specified as part of PAIA, see https://gbv.github.io/paia/paia.html#conditions-and-confirmations. A PAIA client can do a request with explicitly unmet condition to get a list of "storage condition". I must admit that the PAIA spec is not easy at this issue. A client _should_ be able to prevent actual request by sending an undefined condition but the client first needs to check whether the PAIA server actually supports conditions to prevent requesting an item instead of just looking up the conditions. Please open an issue at https://github.com/gbv/paia/issues if needed.
